window.SPLITROOT_APPROVED_ASSETS = {
  schema: "tinyassets.splitroot.approved_assets.v1",
  updated_at_utc: "2026-06-11T18:25:00Z",
  owner_lane: "Ledger",
  purpose: "Standing SPLITROOT asset approval registry. Add newly approved asset URLs here so unit, item, and map-building sessions share one usable list.",
  rules: [
    "Only add assets Jonathan has approved for SPLITROOT use.",
    "Keep rejected assets in rejected_assets so sessions do not re-propose them.",
    "Use current_use to show where an approved asset is currently selected or being considered.",
    "An asset is not in-game until a load log, proof artifact, or captured frame proves it."
  ],
  assets: [
    {
      id: "infinity_blade_collection",
      title: "Infinity Blade Collection",
      url: "https://www.unrealengine.com/blog/free-infinity-blade-collection-marketplace-release",
      approval: "approved_asap",
      source: "Epic announcement",
      lanes: ["units", "items", "map", "vfx"],
      factions: ["VerdantChoir", "KinwildCovenant", "LenswrightCompact"],
      local_status: "blocked_not_locally_obtainable",
      current_use: "Approved ASAP source pool for weapons, warriors, adversaries, effects, and environment pieces once entitlement/download is available.",
      notes: "Do not chase Infinity Blade: Sounds yet; announcement says the sounds pack was removed after rights review.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/3ec7d78b-0230-493c-9e30-e64031bae78c.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with rendered local asset thumbnails after the pack is actually present."
    },
    {
      id: "infinity_blade_weapons",
      title: "Infinity Blade: Weapons",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-weapons",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["items", "units"],
      factions: ["VerdantChoir", "KinwildCovenant", "LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "First-pass item-shop weapon mesh pool.",
      notes: "Use for bows, blades, creature weapons, pressure-tool stand-ins where legally/style appropriate.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/c47ae5a7-2841-479d-a714-b80611e0fdd8.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Thornsprout/pressure weapon thumbnails need the actual weapon meshes rendered after import."
    },
    {
      id: "infinity_blade_warriors",
      title: "Infinity Blade: Warriors",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-characters",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["units"],
      factions: ["VerdantChoir", "LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Heroic humanoid armor/body pool for Thornbound, Gearguard, Briar Saint, and Master Artificer explorations.",
      notes: "Do not use Infinity Blade names/lore in game-facing content.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/201069e9-10d6-45e9-8692-29298f995892.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary source preview only. Replace with rendered local character thumbnails after import."
    },
    {
      id: "infinity_blade_adversaries",
      title: "Infinity Blade: Adversaries",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-enemies",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "not_downloaded",
      current_use: "Creature and monster body pool, especially Kinwild and neutral encounters.",
      notes: "Good upgrade pool for Kinwild after current lizard/wolf placeholders.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/6de10982-b8c4-4c55-9e55-fcfd0e775183.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with rendered local creature thumbnails after import."
    },
    {
      id: "infinity_blade_effects",
      title: "Infinity Blade: Effects",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-effects",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["items", "units", "vfx"],
      factions: ["VerdantChoir", "KinwildCovenant", "LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Spell, hit, shop-item, beacon, hero, and tech-building VFX pool.",
      notes: "Lenswright VFX must avoid gunpowder/muzzle-flash reads.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/8de37728-4caf-4b07-a7fd-7cbf8f2daa46.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with captured VFX thumbnails after import."
    },
    {
      id: "infinity_blade_grass_lands",
      title: "Infinity Blade: Grass Lands",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-plain-lands",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["map"],
      factions: ["VerdantChoir"],
      local_status: "not_downloaded",
      current_use: "Verdant and neutral set-dressing pool if still available.",
      notes: "Map-building session can use this for Verdant-adjacent dressing.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/f9b0f062-6634-4b0b-af45-84329fae8137.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with local environment-piece renders after import."
    },
    {
      id: "infinity_blade_fire_lands",
      title: "Infinity Blade: Fire Lands",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-fire-lands",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["map", "items"],
      factions: ["LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Forge, siege, molten tech-building, and pressure-device dressing if still available.",
      notes: "Keep Lenswright fire/alchemy distinct from gunpowder.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/a751e2da-71b2-47ab-9b2d-5d93305d2dee.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with local forge/device-piece renders after import."
    },
    {
      id: "infinity_blade_ice_lands",
      title: "Infinity Blade: Ice Lands",
      url: "https://www.unrealengine.com/marketplace/en-US/product/infinity-blade-ice-lands",
      approval: "approved_asap",
      source: "Unreal Marketplace",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "not_downloaded",
      current_use: "Stone/ice ruins and neutral encounter dressing if still available.",
      notes: "Useful for north/neutral side zones rather than core faction identity.",
      thumbnail: "https://gamefromscratch.com/wp-content/uploads/2020/07/8eea9a30-7039-42f2-9359-5f5c5e1782e8.png",
      thumbnail_quality: "source_article_preview",
      thumbnail_status: "blocked_not_local",
      thumbnail_note: "Temporary collection overview only. Replace with local ruin/environment renders after import."
    },
    {
      id: "paragon_the_fey",
      title: "Paragon: The Fey",
      url: "https://www.fab.com/listings/9afbcde6-4a14-4018-95c3-2f3a2e1da858",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["VerdantChoir"],
      local_status: "not_downloaded",
      current_use: "Briar Saint, Grovekeeper, and Verdant magic/nature silhouette candidate.",
      notes: "Bring in only when a Verdant hero/caster row needs it.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/7c8c9938-80b4-4ee0-afa9-0ea94ee8a0cb/0dfce20b-558b-4e8d-ba6a-80e10ea81337.jpg"
    },
    {
      id: "paragon_morigesh",
      title: "Paragon: Morigesh",
      url: "https://www.fab.com/listings/29e67175-fa08-448f-822b-37f411530749",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["VerdantChoir"],
      local_status: "not_downloaded",
      current_use: "Darker Verdant witch/sporecaster candidate.",
      notes: "Best approved pool note for Sporecaster if that unit becomes current.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/71d0eb63-8688-4467-87e0-fa5e5b23698f/d99d3599-23a0-4e0e-bd3c-af62b9a8feec.jpg"
    },
    {
      id: "paragon_greystone",
      title: "Paragon: Greystone",
      url: "https://www.fab.com/listings/122fd7bf-6f12-4304-a930-cccbbacdaebc",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Gearguard heavy armored kit and Master Artificer armor candidate.",
      notes: "Do not use Paragon names in game-facing content.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/0dddac88-0549-4b41-b887-391c5d473328/3b8f0d38-3cb2-4d63-b8e3-c42c88beedb7.jpg"
    },
    {
      id: "paragon_terra",
      title: "Paragon: Terra",
      url: "https://www.fab.com/listings/5ea6bcb6-e43e-4bbe-813f-c19d8c907565",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Shield/tank armor kit for Gearguard or defensive Lenswright row.",
      notes: "Use for shield silhouette, not firearm identity.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/fe52841f-85cd-44f8-916c-6ea7fffc8c76/a6d145f4-9bde-4281-9519-69a31a1b0e9e.jpg"
    },
    {
      id: "paragon_kwang",
      title: "Paragon: Kwang",
      url: "https://www.fab.com/listings/f4c67e92-b976-4b5b-ab9f-4c25b010f6f3",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["LenswrightCompact"],
      local_status: "not_downloaded",
      current_use: "Disciplined melee body if Lenswright needs a close kit; possible Lens Arbalist/Pressure Runner upgrade pool.",
      notes: "Current Pressure Runner uses Rogue until this is needed.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/1f06de65-b07a-4ace-a398-35156b41f882/982fd9cf-84a7-4b83-b2a0-aa34ad6933cd.jpg"
    },
    {
      id: "paragon_khaimera",
      title: "Paragon: Khaimera",
      url: "https://www.fab.com/listings/e7c665c1-8c13-42f0-9152-0753008853d7",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "not_downloaded",
      current_use: "Primary Kinwild hunter or beast-body candidate after the lizard placeholder.",
      notes: "Likely high-value Kinwild upgrade.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d23a8eaa-29f2-42b8-aa9f-6c1615fec540/5ad5b1cd-9989-4e69-bd7d-4460dc422d80.jpg"
    },
    {
      id: "paragon_grux",
      title: "Paragon: Grux",
      url: "https://www.fab.com/listings/8c4bac2c-f7f7-4632-a644-47f4e104f5d8",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "not_downloaded",
      current_use: "Heavy brawler creature kit.",
      notes: "Candidate for heavy Kinwild tech row.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/62b4fb52-6263-48c3-ba8a-078caa1eaab7/0fe9ffd2-9526-4304-8c0b-a54bf8d208d4.jpg"
    },
    {
      id: "paragon_rampage",
      title: "Paragon: Rampage",
      url: "https://www.fab.com/listings/0807cf74-08fd-4a33-8c8d-f33c9439fb1f",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "not_downloaded",
      current_use: "Late-tech creature tank or beast-form item candidate.",
      notes: "Use selectively when the roster has a real tank slot.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d19e98ea-16df-4644-9314-19c6683f420e/4a9581a7-edba-4c9e-9e54-083c44728620.jpg"
    },
    {
      id: "paragon_narbash",
      title: "Paragon: Narbash",
      url: "https://www.fab.com/listings/d8904a0e-9169-4763-b82b-5fcf864235a4",
      approval: "approved_selective",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "not_downloaded",
      current_use: "Pack Caller, support, drummer, or aura-kit candidate.",
      notes: "Best current approved pool note for Kinwild support/hero slot.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/4bf87ef0-49e5-4fd9-978a-4ba3f0bbe693/e75c02c2-6894-432d-a1a6-7c52d912e2a0.jpg"
    },
    {
      id: "fab_15e2afd1",
      title: "Rogue Character Model",
      url: "https://www.fab.com/listings/15e2afd1-11c0-4679-832c-ebbfb6162583",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["units"],
      factions: ["LenswrightCompact", "VerdantChoir"],
      local_status: "ue_imported",
      current_use: "Selected for Lenswright Pressure Runner; first visual-swap candidate for Bracewright; fallback body for Sundial Optic.",
      notes: "Non-AI, 5 rating, 12 reviews. Needs frame verification before claiming in-game use.",
      thumbnail: "thumbs/generated/rogue_character_model.png",
      thumbnail_quality: "local_preview_cropped",
      thumbnail_status: "render_from_imported_asset_pending",
      thumbnail_note: "Generated from the local source preview to remove marketplace text; replace with a clean in-engine render after visual-swap capture is safe.",
      local_path: "Content/Fab_15e2afd1_Rogue_Character_Model"
    },
    {
      id: "fab_bf70b6c1",
      title: "Lizard Kin Warrior Character Rig",
      url: "https://www.fab.com/listings/bf70b6c1-ccd4-4687-8d10-9e49cc1c67c8",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "raw_source_present_import_pending",
      current_use: "Selected for Kinwild Spear Hunter.",
      notes: "Non-AI, 5 rating, 2 reviews. Needs UE import plus rig/animation verification.",
      thumbnail: "thumbs/generated/lizard_kin_warrior.png",
      thumbnail_quality: "local_preview",
      thumbnail_status: "ue_import_pending",
      thumbnail_note: "Local source preview is usable for roster discussion; final proof needs UE import plus rendered in-project capture.",
      local_path: "Content/Fab_bf70b6c1_Lizard_Kin_Warrior_Character_Rig"
    },
    {
      id: "fab_c5747f8f",
      title: "Low Poly wolf",
      url: "https://www.fab.com/listings/c5747f8f-fb80-48c8-a0fd-c663877630c7",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["units"],
      factions: ["KinwildCovenant"],
      local_status: "raw_source_present_import_pending",
      current_use: "Selected for Kinwild Pack Companion.",
      notes: "Non-AI, 5 rating, 2 reviews. Useful for pack readability; may be too low-poly for final art.",
      thumbnail: "thumbs/generated/low_poly_wolf.png",
      thumbnail_quality: "local_preview_cropped",
      thumbnail_status: "ue_import_pending",
      thumbnail_note: "Generated from the local source preview to emphasize the companion silhouette; final proof needs UE import plus rendered in-project capture.",
      local_path: "Content/Fab_c5747f8f_Low_Poly_wolf"
    },
    {
      id: "fab_f065c0cd",
      title: "Fantasy Game Character",
      url: "https://www.fab.com/listings/f065c0cd-7eaf-4c29-b30d-fe935420c665",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["units"],
      factions: ["VerdantChoir"],
      local_status: "ue_imported_placeholder_only",
      current_use: "Selected for Verdant Temporary Runner placeholder.",
      notes: "AI-generated and zero reviews; not a faction identity anchor.",
      thumbnail: "thumbs/generated/fantasy_game_character.png",
      thumbnail_quality: "local_preview",
      thumbnail_status: "render_from_imported_asset_pending",
      thumbnail_note: "Local source preview only; AI-generated placeholder should not become final Verdant identity.",
      local_path: "Content/Fab_f065c0cd_Fantasy_Game_Character"
    },
    {
      id: "fab_a50c1425",
      title: "Free Stylized Assassin",
      url: "https://www.fab.com/listings/a50c1425-a103-48fc-a546-602d3afb5fe1",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["units"],
      factions: ["VerdantChoir"],
      local_status: "raw_source_present_import_pending_low_priority",
      current_use: "Low-priority Verdant shadow-runner placeholder only if needed.",
      notes: "AI-generated; avoid as final unit identity.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/38492652-1fa6-4095-b8a9-2cdf52ab7dc7/8e31ef7f-cf8d-49c3-affc-e3855398605c.png",
      local_path: "Content/Fab_a50c1425_Free_Stylized_Assassin"
    },
    {
      id: "fab_52529a12",
      title: "FANTASTIC - Village Pack",
      url: "https://www.fab.com/listings/52529a12-e88e-41a0-8834-b87306f20c24",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Map-building pool for villages, walls, fences, carts, furniture, flags, stylized nature, and base dressing.",
      notes: "Non-AI, 4.82 rating, 88 reviews.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d98061b7-2650-4086-8708-242020b6a733/5a7a552a-17c8-493d-8444-d1a706ec0874.jpg",
      local_path: "Content/Fab_52529a12_FANTASTIC_Village_Pack"
    },
    {
      id: "fab_705ac651",
      title: "FREE Windmill and Village Buildings Pack",
      url: "https://www.fab.com/listings/705ac651-415d-49cd-9253-754f6e0a99ff",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Village-building and windmill dressing pool.",
      notes: "AI-generated flag in listing metadata; use as placeholder/map dressing with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/e1b38f0c-5bf5-4a48-92ce-3b1ba8c33890/01300c33-86fa-48e5-ab8b-d46311f8a141.png",
      local_path: "Content/Fab_705ac651_FREE_Windmill_Village_Buildings_Pack"
    },
    {
      id: "fab_6f2cd83f",
      title: "Realistic Forest Pack",
      url: "https://www.fab.com/listings/6f2cd83f-8e78-45cf-bb2c-cd05e073e5c7",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Forest dressing pool.",
      notes: "Non-AI, local source payload present.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d64a235f-4545-4695-af09-8d6ff18aaec8/88a6aeaf-5556-484e-a287-3c5ecd8617c3.png",
      local_path: "Content/Fab_6f2cd83f_Realistic_Forest_Pack"
    },
    {
      id: "fab_8a517c31",
      title: "3 English Oak",
      url: "https://www.fab.com/listings/8a517c31-6e78-4a42-b84d-3dc65026660f",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Tree dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/70a06ae8-a556-4239-bf83-cc439b911002/76724ea9-67b9-48fb-8a37-64ddb394c180.jpeg",
      local_path: "Content/Fab_8a517c31_3_English_Oak"
    },
    {
      id: "fab_936eefbf",
      title: "Castle of Rocca Calascio",
      url: "https://www.fab.com/listings/936eefbf-a1ed-46b1-8aff-340dbc4b950b",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Castle/ruin dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/b83cf748-cf89-484f-97cc-4bbf492930f2/d09970f4-5566-4a45-8bf8-c9acc271b89a.jpeg",
      local_path: "Content/Fab_936eefbf_Castle_of_Rocca_Calascio"
    },
    {
      id: "fab_aa50f843",
      title: "Cathedral Clock Tower Titan",
      url: "https://www.fab.com/listings/aa50f843-808e-4e49-bf78-705a8eb85dbe",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map", "units"],
      factions: ["LenswrightCompact", "neutral"],
      local_status: "raw_source_present",
      current_use: "Potential clockwork landmark or large creature/structure study; not selected for current unit roster.",
      notes: "AI-generated; review before any identity use.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/e8417222-612f-4fec-a55d-1235dde79554/a6981c93-abd9-4df2-9e26-11b693f8d495.png",
      local_path: "Content/Fab_aa50f843_Cathedral_Clock_Tower_Titan"
    },
    {
      id: "fab_9bc7b465",
      title: "Dirty stones pile",
      url: "https://www.fab.com/listings/9bc7b465-117c-4309-ae92-ab875f22eaf2",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Terrain/rock prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/2a77fa00-820b-4772-a6bb-9cd5084e99d0/976abf49-ea4c-4dfa-9d30-7a99c26ccc7c.jpeg",
      local_path: "Content/Fab_9bc7b465_Dirty_stones_pile"
    },
    {
      id: "fab_3dc9cf1b",
      title: "Distorted Snowy Peaks 20260126-1424",
      url: "https://www.fab.com/listings/3dc9cf1b-15c7-4fed-a574-df710bb99385",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Terrain/mountain/rock prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/1efb1c1c-f866-4e44-9448-7e84249a42c0/ab3114a4-0468-4d76-9f60-92cbeaaa3990.jpg",
      local_path: "Content/Fab_3dc9cf1b_Distorted_Snowy_Peaks_20260126_1424"
    },
    {
      id: "fab_eea461bd",
      title: "Dwarf's Statue",
      url: "https://www.fab.com/listings/eea461bd-a87c-4cf1-b2bc-e1dc8931405a",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Statue/landmark dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/9bdb5a3e-990d-4d1c-8b96-b45fb07fe140/775218b6-e524-47bc-aaa9-017000c81d25.jpeg",
      local_path: "Content/Fab_eea461bd_Dwarf_s_Statue"
    },
    {
      id: "fab_e12de9d5",
      title: "ElderBoom Hollow Massive Medieval Village Environment",
      url: "https://www.fab.com/listings/e12de9d5-be28-40df-a387-42ae6f84e05c",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Large medieval village environment pool.",
      notes: "Non-AI. Large payload; map session should watch perf.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/6a91256f-ca2d-4d29-a637-3dba4ba09b21/7599460e-90f8-4922-8e57-3bcc4798ca9f.jpg",
      local_path: "Content/Fab_e12de9d5_ElderBoom_Hollow_Massive_Medieval_Vi"
    },
    {
      id: "fab_f88257fb",
      title: "Fantasy Village House in the Dark Forest",
      url: "https://www.fab.com/listings/f88257fb-bbb1-424e-9e2d-3d6f48be76e8",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Forest village house dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/5f07ba28-c90d-4266-aa40-9cad6e38f154/0a2d09fa-220a-4f4d-924a-17a276b1d86a.jpg",
      local_path: "Content/Fab_f88257fb_Fantasy_Village_House_in_the_Dark_Fo"
    },
    {
      id: "fab_6e579cff",
      title: "Faymere River Village A Forgotten Medieval Gem",
      url: "https://www.fab.com/listings/6e579cff-a28f-499b-a0ad-30649d40774a",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Medieval river village and terrain prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/ebceabc6-cc01-4ff1-a66d-8f3f228d9abc/2f7c35c0-ff12-4aca-b6f9-c13a332c1515.jpg",
      local_path: "Content/Fab_6e579cff_Faymere_River_Village_A_Forgotten_Me"
    },
    {
      id: "fab_729cfcec",
      title: "Forest ground soil pine - free",
      url: "https://www.fab.com/listings/729cfcec-a21d-451e-b035-651eca796d12",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Forest ground material/soil dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/3ba9bf9e-624f-4c3e-a733-c29edf03a07a/8694643e-8c2d-4ff6-a7a8-f1dfc73bfe50.jpeg",
      local_path: "Content/Fab_729cfcec_Forest_ground_soil_pine_free"
    },
    {
      id: "fab_f255de9f",
      title: "free fantasy architecture w2r_16",
      url: "https://www.fab.com/listings/f255de9f-1525-48df-abf7-76f890239c4c",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Small fantasy architecture pool.",
      notes: "AI-generated; use as placeholder with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/25f5eed2-7ab6-45c4-82ea-95e10bf7be19/404ef45a-b304-4161-8419-1de2d7b42fd4.jpg",
      local_path: "Content/Fab_f255de9f_free_fantasy_architecture_w2r_16"
    },
    {
      id: "fab_ce35c108",
      title: "Free Hill Rock Mountain Terrain - 3d environment game asset",
      url: "https://www.fab.com/listings/ce35c108-2809-48c3-b5cd-8484e6e1a0ef",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Mountain/terrain/rock/tree pool.",
      notes: "AI-generated metadata flag; use as environment placeholder with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/71539c46-55e9-482c-b8fa-439a60beaa16/805fb801-6617-4c90-91be-a417114bcf6b.jpg",
      local_path: "Content/Fab_ce35c108_Free_Hill_Rock_Mountain_Terrain_3d_e"
    },
    {
      id: "fab_b4907566",
      title: "Free Mountain Terrain, Rock and Tree - 3d game assets",
      url: "https://www.fab.com/listings/b4907566-d56d-4bf0-98ea-e4d67e266bcc",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Mountain/terrain/rock/tree pool.",
      notes: "AI-generated metadata flag; use as environment placeholder with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/40ad4aed-57eb-4cb7-87ed-dc8cfd82aff7/d8f4f611-1330-41a2-a59c-99933e8527e7.jpg",
      local_path: "Content/Fab_b4907566_Free_Mountain_Terrain_Rock_and_Tree"
    },
    {
      id: "fab_8b804edb",
      title: "Large Medieval Building",
      url: "https://www.fab.com/listings/8b804edb-3998-425c-8b55-b15154da9c94",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Large medieval building/base dressing pool.",
      notes: "AI-generated metadata flag; use with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/8abff520-74e4-46d0-aa93-0733ae5f9fcf/3ddac94f-039c-46bc-825c-a5cb0fbc711b.png",
      local_path: "Content/Fab_8b804edb_Large_Medieval_Building"
    },
    {
      id: "fab_76963e56",
      title: "Medieval Castle Tower 4",
      url: "https://www.fab.com/listings/76963e56-0bef-47d3-b66e-39bc352e7997",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Tower/base dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/2ebd1c9e-8b51-4cc3-a9e1-e28034028163/07a318a7-451c-4b8c-aca1-c13b7178abf1.png",
      local_path: "Content/Fab_76963e56_Medieval_Castle_Tower_4"
    },
    {
      id: "fab_18418ed8",
      title: "Medieval Fountain Empty (Free)",
      url: "https://www.fab.com/listings/18418ed8-e759-4408-bb36-3ff628d1fdd2",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Settlement plaza/fountain dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/ca3062c2-5862-47a4-8b7d-3c53816465d0/49cd3073-7bd8-4434-84dc-0f80e1844794.jpeg",
      local_path: "Content/Fab_18418ed8_Medieval_Fountain_Empty_Free"
    },
    {
      id: "fab_73e37a6f",
      title: "Medieval Tavern",
      url: "https://www.fab.com/listings/73e37a6f-b7d7-41f1-b26d-ec1d627b795e",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Town/village dressing pool.",
      notes: "AI-generated metadata flag; use with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/cdd7a9db-386f-494d-a2ae-9615c97878c1/47094b1a-d416-46b6-b446-a4f9b3e94d37.png",
      local_path: "Content/Fab_73e37a6f_Medieval_Tavern"
    },
    {
      id: "fab_b40acc92",
      title: "Medieval Torch (Free)",
      url: "https://www.fab.com/listings/b40acc92-21e1-4d92-9248-2ecce53fc99b",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map", "items"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Torch/light prop and possible item-shop prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/39126192-fa6b-4d81-af03-130b344e811d/1fc57bdc-82a7-44ee-869b-122c11ac79fd.jpeg",
      local_path: "Content/Fab_b40acc92_Medieval_Torch_Free"
    },
    {
      id: "fab_43679e75",
      title: "Megaplants: European Hornbeam",
      url: "https://www.fab.com/listings/43679e75-6ed0-4b03-9288-9e2bc49376d2",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "High-quality tree/foliage pool.",
      notes: "Non-AI Quixel Megaplants source.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/e022a97e-ae14-48c7-995b-fd66714d531d/bd4c723f-bf75-43d2-9784-df1a21f1f618.jpg",
      local_path: "Content/Fab_43679e75_Megaplants_European_Hornbeam"
    },
    {
      id: "fab_e1d7c88a",
      title: "Moss covered rock pile",
      url: "https://www.fab.com/listings/e1d7c88a-308e-4e74-ae56-4fbe505c15b3",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Mossy rock and Verdant/forest terrain dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/04f0d45f-c3ef-4e3a-bd82-e77c2ff32da5/213bb31e-4eab-45da-a316-8c4a10e3ffeb.jpeg",
      local_path: "Content/Fab_e1d7c88a_Moss_covered_rock_pile"
    },
    {
      id: "fab_62667742",
      title: "Mountain Surrounded Village Environment",
      url: "https://www.fab.com/listings/62667742-324a-4564-a288-316fe92c0059",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Village plus terrain environment pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/333113c4-d72d-4994-af46-53a1debe7191/f1278e68-4fdb-4b7f-b084-3b4c9a4973f8.jpg",
      local_path: "Content/Fab_62667742_Mountain_Surrounded_Village_Environm"
    },
    {
      id: "fab_48bc73b5",
      title: "Old green stump",
      url: "https://www.fab.com/listings/48bc73b5-c87f-4b63-aa20-fea9fc7ab70c",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Stump/forest dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/a0446f5b-3038-4dd6-a8c8-58c393e745f5/579f5420-dbf1-4170-8d92-f056fa3c3bd6.jpeg",
      local_path: "Content/Fab_48bc73b5_Old_green_stump"
    },
    {
      id: "fab_483c61f0",
      title: "Old red wood tree stump",
      url: "https://www.fab.com/listings/483c61f0-9df5-4569-a72a-f746ae0f28a7",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Stump/forest dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/f88d3d8b-11a6-4841-9021-c25cae3e6655/ea3d8eaf-c296-4af4-a286-8772d8b9e272.jpeg",
      local_path: "Content/Fab_483c61f0_Old_red_wood_tree_stump"
    },
    {
      id: "fab_9a372206",
      title: "Ponte del Toro | ITALY",
      url: "https://www.fab.com/listings/9a372206-0d12-4fc0-957e-4ea166e520f6",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Bridge/point-of-interest dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/867e7380-f0e5-4164-9aab-087689705581/ef3fbc54-94de-4cba-9d3c-481418f908f5.jpg",
      local_path: "Content/Fab_9a372206_Ponte_del_Toro_ITALY"
    },
    {
      id: "fab_16b5f712",
      title: "Rock terrain with light snow",
      url: "https://www.fab.com/listings/16b5f712-2318-4bc0-b922-b6f5872a5139",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Snow/rock terrain prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d06632f0-02e4-4e25-ac1b-1478255a80ac/acf19411-5d72-4f44-8543-32feca73674e.jpeg",
      local_path: "Content/Fab_16b5f712_Rock_terrain_with_light_snow"
    },
    {
      id: "fab_7df266f1",
      title: "rocks pack",
      url: "https://www.fab.com/listings/7df266f1-1813-4fc1-8548-cb115e1d2bd8",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Rock prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/d27d9656-b39a-40e0-9b92-63ac33d36da9/0ffefb6b-e189-41f4-a206-356771ec339f.jpeg",
      local_path: "Content/Fab_7df266f1_rocks_pack"
    },
    {
      id: "fab_64fe81cc",
      title: "Rustic Medieval Cliffside House",
      url: "https://www.fab.com/listings/64fe81cc-3e9c-46f6-8290-1e5834a0478d",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Cliffside house/base dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/da81ddf3-03ef-436d-b266-9932ec8bee04/cad534ac-6cf9-4e76-a0ed-d30bb8738d24.jpg",
      local_path: "Content/Fab_64fe81cc_Rustic_Medieval_Cliffside_House"
    },
    {
      id: "fab_02cde3bc",
      title: "Sacre Coeur",
      url: "https://www.fab.com/listings/02cde3bc-f807-4560-b433-e8a85f2521ee",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Large landmark/architecture dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/c128a858-cad4-45b8-9873-e1d967bfbe74/e99ca485-a93c-4ac0-8382-8ae9320799af.jpeg",
      local_path: "Content/Fab_02cde3bc_Sacre_Coeur"
    },
    {
      id: "fab_695e7e6a",
      title: "Small Medieval Building",
      url: "https://www.fab.com/listings/695e7e6a-bb74-4985-8e57-cfadb88158d9",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir", "LenswrightCompact"],
      local_status: "raw_source_present",
      current_use: "Small building/base dressing pool.",
      notes: "AI-generated metadata flag; use with review.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/8de304a1-d153-476f-acae-cc96feab8882/565245a7-a829-44d1-a197-1efbcfa1b294.png",
      local_path: "Content/Fab_695e7e6a_Small_Medieval_Building"
    },
    {
      id: "fab_6a11b64a",
      title: "Snow-Covered Trees Stylized Winter Nature - Free low-poly 3D models",
      url: "https://www.fab.com/listings/6a11b64a-540d-4348-89b1-2a0145575523",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Snow tree dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/2b35c5ea-e88a-4095-b84d-fc69e130df9f/a7d6e090-a648-470f-9bc6-7499a07d9c31.jpg",
      local_path: "Content/Fab_6a11b64a_Snow_Covered_Trees_Stylized_Winter_N"
    },
    {
      id: "fab_4bdf00c1",
      title: "Tavern",
      url: "https://www.fab.com/listings/4bdf00c1-7b93-4b10-9a56-428ed8f37b3d",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral", "VerdantChoir"],
      local_status: "raw_source_present",
      current_use: "Tavern/town dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/e03151e3-4fac-48bc-b969-bcef4c65cdbc/78d2ec8c-f8a0-48c2-9c73-1f98dc46c22c.jpeg",
      local_path: "Content/Fab_4bdf00c1_Tavern"
    },
    {
      id: "fab_1ed49b08",
      title: "Torre d'en Galmes Sala Hipostila",
      url: "https://www.fab.com/listings/1ed49b08-8493-4cc6-bf85-195fa98dd525",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Historical point-of-interest/terrain dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/9b4b01a9-d79a-49a4-8846-a0260592452a/ec5ed6dc-2b3f-45b2-8931-c14555856c21.jpeg",
      local_path: "Content/Fab_1ed49b08_Torre_d_en_Galm_s_Sala_Hip_stila"
    },
    {
      id: "fab_0f3c28a0",
      title: "Wall of ice",
      url: "https://www.fab.com/listings/0f3c28a0-2c1a-4c37-8000-796b70d8f11a",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map", "items"],
      factions: ["neutral"],
      local_status: "raw_source_present",
      current_use: "Ice wall/terrain prop pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/3b56d668-e43e-402b-9168-ed98e0d3c32b/e05e9714-1672-4117-bd19-2ec7e992320c.jpeg",
      local_path: "Content/Fab_0f3c28a0_Wall_of_ice"
    },
    {
      id: "fab_4020b8f7",
      title: "Wooden House and Path in a Fantasy Nordic Forest",
      url: "https://www.fab.com/listings/4020b8f7-4884-440e-94c9-7533c84bcb48",
      approval: "approved_local_library",
      source: "Fab",
      lanes: ["map"],
      factions: ["VerdantChoir", "neutral"],
      local_status: "raw_source_present",
      current_use: "Fantasy forest house/path dressing pool.",
      notes: "Non-AI.",
      thumbnail: "https://media.fab.com/image_previews/gallery_images/469cf506-a4e4-4080-8074-2e39174a1c2c/16f3e1fa-b67d-4c81-86ed-116b22ffa0cf.jpg",
      local_path: "Content/Fab_4020b8f7"
    }
  ],
  rejected_assets: [
    {
      id: "rejected_synty_sidekick",
      title: "FREE Starter Pack - Sidekick Modular Characters by Synty",
      url: "https://www.fab.com/listings/8d8e9639-d93f-4f1d-8332-32ae0ef14bca",
      reason: "Not approved by Jonathan."
    },
    {
      id: "rejected_free_rigged_knights",
      title: "Free Rigged Knights - Game Ready Characters with Animations",
      url: "https://www.fab.com/listings/ada783ab-ca49-4b44-a555-0e51807e8fce",
      reason: "Not approved by Jonathan."
    },
    {
      id: "rejected_cursed_knight",
      title: "Cursed Knight - UE5 Character on Sketchfab",
      url: "https://sketchfab.com/3d-models/cursed-knight-ue5-character-game-ready-f204e0ad3af645bcb0ecffd9e9ae9a15",
      reason: "Not approved by Jonathan."
    }
  ]
};
